# validatingwebhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-registry
webhooks:
  - name: io.ydzs.admission-registry
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: default
        name: admission-registry
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVT2hYT1NSeXBrQXl5ejU4dWU2a2NDTHBxSW4wd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl5TVRFeE1EQTVNVGN3TUZvWERUSTNNVEV3T1RBNU1UY3dNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMnh3VXlhTnB5anhTL3pVeWlJNmgKU0VHQTIzbTRvNGhEWXJKL1VmOXhWNHg0c0NXQmRBZ2dYaG9WRWlaNnhoT2QxTUJwYW9NdFVrNHo4YmFJSXB3TAppYy9xbTNVTVp3QVF0SzFDTzVjcmUxSysvQjE2SU1TN3Joa2RSbGFwczZtcGxiNDduN3o3VGVnYXpOd2ZjbmM0CklWOGh5MGpqWkFZanRTZU1XT1FaQnNkdzhpZ1ROTFM5NVRlM1RDS21LQU1OSE1pdWJ0czhES2RVc3A5cldyZ2EKYy9xUElERlIyY00xaWpiUXdLSkY1NnRISXBKdHEwWjVZWmk4YWVwdVcyQit0T0hHR2ZaWEZKdEs1WGg2NGJkVApYTC9yUU1Id1grbVI5elNUOHNyeEpPUlMySVBNYTVhc1FKS0lSTEh5QVRoa0lnZkQ4YzBUUFNOWDFlK3RWc3RYCkt3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVUnUxUHRJaWtFMWxYenBpZGFIaVYxY3M2d2lJd0h3WURWUjBqQkJnd0ZvQVVSdTFQdElpawpFMWxYenBpZGFIaVYxY3M2d2lJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNaUl0SXNYRGhmbXdncnk1MW1HCldGRE1CeDRQNVVMVVNhQWo5TFE2TUxSd0xtNHh1aVlsbFVkOXppZTRsWjV4RWQyZUM4Wk5Eby80cEFXSld4NjIKTzYwekorWjZDWFFqYzlrNjBpYTVLOUV1T0RGZDFRc1hMY2c4YzZpMU1Ea0ttUzJ2WEFpeXJWbnhnTUYrM01QVApWVk9yVTZBekJpRVNpNnBGNTVJTzdqWXZlMlN1RE9PYzhsMDB0Wm9CdU5vZFIxS0ZQaXlpOVE1NmtQT2xJenhxCnJHS0ZJaTBISUc4V2ZOa2pTZXpwZXJMM2VPMU15ZWtuUzA1UVArYUxpMWxJaVZ0dUROZ1liSmc5UlVJY3hrTFcKWjhKdUFKclV1WlpJYkdiT1p3eUdqZVU4bHNraFNpV0NHcXFCd2lYdWU2T20rZElRNGM2dmpqaTZIbFJ1S3M0SwpzSjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-registry-mutate
webhooks:
  - name: io.ydzs.admission-registry-mutate
    clientConfig:
      service:
        namespace: default
        name: admission-registry
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVT2hYT1NSeXBrQXl5ejU4dWU2a2NDTHBxSW4wd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl5TVRFeE1EQTVNVGN3TUZvWERUSTNNVEV3T1RBNU1UY3dNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMnh3VXlhTnB5anhTL3pVeWlJNmgKU0VHQTIzbTRvNGhEWXJKL1VmOXhWNHg0c0NXQmRBZ2dYaG9WRWlaNnhoT2QxTUJwYW9NdFVrNHo4YmFJSXB3TAppYy9xbTNVTVp3QVF0SzFDTzVjcmUxSysvQjE2SU1TN3Joa2RSbGFwczZtcGxiNDduN3o3VGVnYXpOd2ZjbmM0CklWOGh5MGpqWkFZanRTZU1XT1FaQnNkdzhpZ1ROTFM5NVRlM1RDS21LQU1OSE1pdWJ0czhES2RVc3A5cldyZ2EKYy9xUElERlIyY00xaWpiUXdLSkY1NnRISXBKdHEwWjVZWmk4YWVwdVcyQit0T0hHR2ZaWEZKdEs1WGg2NGJkVApYTC9yUU1Id1grbVI5elNUOHNyeEpPUlMySVBNYTVhc1FKS0lSTEh5QVRoa0lnZkQ4YzBUUFNOWDFlK3RWc3RYCkt3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVUnUxUHRJaWtFMWxYenBpZGFIaVYxY3M2d2lJd0h3WURWUjBqQkJnd0ZvQVVSdTFQdElpawpFMWxYenBpZGFIaVYxY3M2d2lJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNaUl0SXNYRGhmbXdncnk1MW1HCldGRE1CeDRQNVVMVVNhQWo5TFE2TUxSd0xtNHh1aVlsbFVkOXppZTRsWjV4RWQyZUM4Wk5Eby80cEFXSld4NjIKTzYwekorWjZDWFFqYzlrNjBpYTVLOUV1T0RGZDFRc1hMY2c4YzZpMU1Ea0ttUzJ2WEFpeXJWbnhnTUYrM01QVApWVk9yVTZBekJpRVNpNnBGNTVJTzdqWXZlMlN1RE9PYzhsMDB0Wm9CdU5vZFIxS0ZQaXlpOVE1NmtQT2xJenhxCnJHS0ZJaTBISUc4V2ZOa2pTZXpwZXJMM2VPMU15ZWtuUzA1UVArYUxpMWxJaVZ0dUROZ1liSmc5UlVJY3hrTFcKWjhKdUFKclV1WlpJYkdiT1p3eUdqZVU4bHNraFNpV0NHcXFCd2lYdWU2T20rZElRNGM2dmpqaTZIbFJ1S3M0SwpzSjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None